package com.example.redditnews.domain.models

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity( tableName  = "favoriteArticles")
data class ArticleFavorite(
    @PrimaryKey
    val id: String  ,
    val allow_live_comments: Boolean ? = null,
    val approved_at_utc: Any    ? = null,
    val approved_by: Any   ? = null,
    val archived: Boolean   ? = null,
    val author: String   ? = null,
    val author_flair_background_color: Any ? = null  ,
    val author_flair_css_class: Any   ? = null,
    val author_flair_text: Any   ? = null,
    val author_flair_text_color: Any   ? = null,
    val author_flair_type: String   ? = null,
    val author_fullname: String   ? = null,
    val author_is_blocked: Boolean   ? = null,
    val author_patreon_flair: Boolean   ? = null,
    val author_premium: Boolean   ? = null,
    val banned_at_utc: Any   ? = null,
    val banned_by: Any   ? = null,
    val can_gild: Boolean ? = null,
    val can_mod_post: Boolean   ? = null,
    val category: Any   ? = null,
    val clicked: Boolean   ? = null,
    val content_categories: Any   ? = null,
    val contest_mode: Boolean   ? = null,
    val created: Int   ? = null,
    val created_utc: Int   ? = null,
    val discussion_type: Any   ? = null,
    val distinguished: Any   ? = null,
    val domain: String   ? = null,
    val downs: Int   ? = null,
    val gilded: Int   ? = null,
    val hidden: Boolean   ? = null,
    val hide_score: Boolean   ? = null,
    val is_created_from_ads_ui: Boolean  ? = null ,
    val is_crosspostable: Boolean   ? = null,
    val is_meta: Boolean   ? = null,
    val is_original_content: Boolean   ? = null,
    val is_reddit_media_domain: Boolean   ? = null,
    val is_robot_indexable: Boolean   ? = null,
    val is_self: Boolean   ? = null,
    val is_video: Boolean   ? = null,
    val likes: Any   ? = null,
    val link_flair_background_color: String   ? = null,
    val link_flair_css_class: Any   ? = null,
    val link_flair_text: Any   ? = null,
    val link_flair_text_color: String  ? = null ,
    val link_flair_type: String   ? = null,
    val locked: Boolean   ? = null,
    val media_only: Boolean   ? = null,
    val mod_note: Any   ? = null,
    val mod_reason_by: Any   ? = null,
    val mod_reason_title: Any   ? = null,
    val name: String   ? = null,
    val no_follow: Boolean   ? = null,
    val num_comments: Int   ? = null,
    val num_crossposts: Int   ? = null,
    val num_reports: Any   ? = null,
    val over_18: Boolean   ? = null,
    val parent_whitelist_status: String  ? = null ,
    val permalink: String   ? = null,
    val pinned: Boolean   ? = null,
    val pwls: Int   ? = null,
    val quarantine: Boolean  ? = null ,
    val removal_reason: Any   ? = null,
    val removed_by: Any   ? = null,
    val removed_by_category: Any  ? = null ,
    val report_reasons: Any   ? = null,
    val saved: Boolean   ? = null,
    val score: Int   ? = null,
    val send_replies: Boolean  ? = null ,
    val spoiler: Boolean   ? = null,
    val stickied: Boolean   ? = null,
    val subreddit: String   ? = null,
    val subreddit_id: String   ? = null,
    val subreddit_name_prefixed: String  ? = null ,
    val subreddit_subscribers: Int   ? = null,
    val subreddit_type: String   ? = null,
    val suggested_sort: Any   ? = null,
    val thumbnail: String   ? = null,
    val title: String   ? = null,
    val top_awarded_type: Any   ? = null,
    val total_awards_received: Int   ? = null,
    val ups: Int   ? = null,
    val upvote_ratio: Double  ? = null ,
    val url: String   ? = null,
    val view_count: Any   ? = null,
    val visited: Boolean   ? = null,
    val whitelist_status: String = "" ,
    val wls: Int = 1
)